version: '3.4'
services:
  charity-cms:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: dockerfile-dev
    command: yarn develop
    ports:
      - "1337:1337"
    volumes:
      - ./api:/charity-cms/api
      - ./components:/charity-cms/components
      - ./config:/charity-cms/config
      - ./extensions:/charity-cms/extensions
      - ./public:/charity-cms/public