apiVersion: v1
kind: Namespace
metadata:
  name: {{{M3_NAMESPACE}}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
  namespace: '{{{M3_NAMESPACE}}}'
  labels:
    project: '{{{M3_PROJECT}}}'
    environment: '{{{M3_ENVIRONMENT}}}'
    componenet: '{{{M3_COMPONENET}}}'
    application: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
    version: '{{{M3_VERSION}}}'
spec:
  replicas: {{{M3_REPLICAS}}}
  selector:
    matchLabels:
      application: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
  template:
    metadata:
      labels:
        project: '{{{M3_PROJECT}}}'
        environment: '{{{M3_ENVIRONMENT}}}'
        componenet: '{{{M3_COMPONENET}}}'
        application: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
    spec:
      containers:
        - name: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
          image: '{{{M3_IMAGE}}}:{{{M3_VERSION}}}'
          envFrom:
            - secretRef:
                name: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
          env:
            - name: PORT
              value: '{{{M3_PORT}}}'
          ports:
            - name: web
              containerPort: {{{M3_PORT}}}
              protocol: TCP
        - name: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}-ar'
          image: '{{{M3_IMAGE}}}:{{{M3_VERSION}}}'
          envFrom:
            - secretRef:
                name: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}-ar'
          env:
            - name: PORT
              value: '{{{M3_PORT_AR}}}'
          ports:
            - name: web-ar
              containerPort: {{{M3_PORT_AR}}}
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
  namespace: '{{{M3_NAMESPACE}}}'
  labels:
    project: '{{{M3_PROJECT}}}'
    environment: '{{{M3_ENVIRONMENT}}}'
    componenet: '{{{M3_COMPONENET}}}'
    application: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
    version: '{{{M3_VERSION}}}'
spec:
  selector:
    application: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: {{{M3_PORT}}}
    - name: web-ar
      protocol: TCP
      port: 81
      targetPort: {{{M3_PORT_AR}}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
  namespace: '{{{M3_NAMESPACE}}}'
  labels:
    project: '{{{M3_PROJECT}}}'
    environment: '{{{M3_ENVIRONMENT}}}'
    componenet: '{{{M3_COMPONENET}}}'
    application: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
    version: '{{{M3_VERSION}}}'
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
spec:
  rules:
    - host: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}.m3ntorship.net'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
                port:
                  number: 80
    - host: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}-ar.m3ntorship.net'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
                port:
                  number: 81      
