name: deploy ghiras-cms to m3ntorship-dev cluster

# trigger
on:
  push:
    branches:
      - develop
env: 
  M3_ORGANIZATION: ${{github.event.organization.login}}
  M3_REPOSITORY: ${{github.event.repository.name}}
  M3_PROJECT: ghiras
  M3_COMPONENET: cms
  M3_ENVIRONMENT: dev
  M3_NAMESPACE: '${{github.event.organization.login}}-${{github.event.repository.name}}-dev'
  M3_DEPLOYMENT_PATH: deploy/cms
  M3_TEMP_DIR: temp
  M3_REPLICAS: '1'
  
  M3_DOCKER_FILE: Dockerfile
  M3_IMAGE: m3ntorshipci/ghiras-cms
  M3_PORT: '1337'
  M3_PORT_AR: '1338'
  M3_MEMORY: '200Mi'
  M3_CPU: '50m'
jobs:
  
  deploy_dev:
    runs-on: ubuntu-latest
    env:
      M3_NAMESPACE: 'nile'
      M3_VERSION: ${{ needs.prepare.outputs.version }}
      M3_TEMP_DIR: temp
      M3_DEPLOYMENT_PATH: deploy/cms
      M3_PROJECT: ghiras
      M3_COMPONENET: cms
      M3_ENVIRONMENT: dev
      M3_ORGANIZATION: ayoub
      M3_REPOSITORY: ayoub-repo

    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-kubectl@v1
      - name: Kubectl configuration
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_DEV }}" | base64 -d -i > ~/.kube/config
      - name: install moustache
        run: |
          curl -sSL https://git.io/get-mo -o mo
          chmod +x mo
          sudo mv mo /usr/local/bin
          echo "works" | mo
      
      - name: deployment-preparation
        run: |
          echo $M3_NAMESPACE
          mkdir -p $M3_TEMP_DIR
          
      # decrypt secrets
      - name: decrypt-and-create-secrets
        env:
          M3_TEMP_SECRETS_DIR: temp-secrets
          M3_ENCRYPTION_PHRASE: ${{secrets.M3NTORSHIP_ENCRYPTION_PHRASE}}
          M3_ENCRYPTED_SECRETS_DIR: secrets
          
        run: |
          echo $M3_ENCRYPTION_PHRASE
          gpg --quiet --batch --yes --decrypt --passphrase="$M3_ENCRYPTION_PHRASE" ghiras-cms-dev-temp.env.gpg


          # mkdir -p $M3_TEMP_SECRETS_DIR
          # for f in $(find $M3_DEPLOYMENT_PATH/$M3_ENCRYPTED_SECRETS_DIR -maxdepth 1 -type f); do gpg --quiet --batch --yes --decrypt --passphrase="$M3_ENCRYPTION_PHRASE" "$f" > "$M3_TEMP_SECRETS_DIR/$(basename -s .gpg $f)"; done

          # kubectl create secret generic $M3_PROJECT-$M3_COMPONENET-$M3_ENVIRONMENT-temp --from-env-file=$M3_TEMP_SECRETS_DIR/ghiras-cms-dev-temp.env -n $M3_NAMESPACE --dry-run=client
          # kubectl create secret generic $M3_PROJECT-$M3_COMPONENET-$M3_ENVIRONMENT-temp --from-env-file=$M3_TEMP_SECRETS_DIR/ghiras-cms-dev-temp.env -n $M3_NAMESPACE --dry-run=client > $M3_TEMP_DIR/ghiras-cms-dev-temp.yaml
          
      # # deploy dev
      # - name: deploy-dev
      #   run: |
      #     ls -al $M3_TEMP_DIR
      #     cat $M3_TEMP_DIR/ghiras-cms-dev-temp.yaml
      #     for f in $M3_DEPLOYMENT_PATH/apply/*; do mo -u "$f" > $M3_TEMP_DIR/"$(basename $f)"; done
      #     kubectl apply -f $M3_TEMP_DIR
      
      # #cleanup temp directories
      # - name: clean-temp-files
      #   run: rm -rf $M3_TEMP_DIR $M3_TEMP_SECRETS_DIR