name: deploy ghiras-cms to m3ntorship-dev cluster

# trigger
on:
  push:
    branches:
      - xdevelop
env:
  # COMMON deployment envs
  M3_ORGANIZATION: ${{github.event.organization.login}}
  M3_REPOSITORY: ${{github.event.repository.name}}
  M3_PROJECT: ghiras
  M3_COMPONENET: cms
  M3_ENVIRONMENT: dev
  M3_NAMESPACE: '${{github.event.organization.login}}-${{github.event.repository.name}}-dev'
  M3_DEPLOYMENT_PATH: deploy/cms
  M3_TEMP_DIR: temp
  M3_REPLICAS: '1'
  # posts service
  M3_DOCKER_FILE: Dockerfile
  M3_IMAGE: m3ntorshipci/ghiras-cms
  M3_PORT: '1337'
  M3_PORT_AR: '1338'
  M3_MEMORY: '200Mi'
  M3_CPU: '50m'
  M3_TEMP_SECRETS_DIR: temp-secrets
  M3_ENCRYPTION_PHRASE: ${{secrets.M3NTORSHIP_ENCRYPTION_PHRASE}}
  M3_ENCRYPTED_SECRETS_DIR: secrets

jobs:
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-kubectl@v1
      - name: Kubectl configuration
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_DEV }}" | base64 -d -i > ~/.kube/config
      - name: install moustache
        run: |
          curl -sSL https://git.io/get-mo -o mo
          chmod +x mo
          sudo mv mo /usr/local/bin
          echo "works" | mo
      
      - name: deployment-preparation
        run: |
          echo $M3_NAMESPACE
          mkdir -p $M3_TEMP_SECRETS_DIR $M3_TEMP_DIR
      
      # decrypt and create secrets k8s definitions/resources
      - name: decrypt-and-create-secrets          
        run: |

          for f in $(find $M3_DEPLOYMENT_PATH/$M3_ENCRYPTED_SECRETS_DIR -maxdepth 1 -type f); do gpg --quiet --batch --yes --decrypt --passphrase="$M3NTORSHIP_ENCRYPTION_PHRASE" "$f" > "$M3_TEMP_SECRETS_DIR/$(basename -s .gpg $f)"; done

          kubectl create secret generic $M3_PROJECT-$M3_COMPONENET-$M3_ENVIRONMENT --from-env-file=$M3_TEMP_SECRETS_DIR/ghiras-cms-dev.env -n $M3_NAMESPACE --dry-run=client -o yaml > $M3_TEMP_DIR/ghiras-cms-dev.yaml
          kubectl create secret generic $M3_PROJECT-$M3_COMPONENET-$M3_ENVIRONMENT-ar --from-env-file=$M3_TEMP_SECRETS_DIR/ghiras-cms-dev-ar.env -n $M3_NAMESPACE --dry-run=client -o yaml > $M3_TEMP_DIR/ghiras-cms-dev-ar.yaml
          
          #create regular k8s resources
      - name: bind-k8s-template
        run: |
          for f in $M3_DEPLOYMENT_PATH/apply/*; do mo -u "$f" > $M3_TEMP_DIR/"$(basename $f)"; done

      # deploy everything
      - name: deploy
        run: |
          kubectl apply -f $M3_TEMP_DIR
      
      #cleanup temp directories
      - name: clean-temp-files
        run: rm -rf $M3_TEMP_DIR $M3_TEMP_SECRETS_DIR