name: deploy ghiras-cms to m3ntorship-dev cluster

# trigger
on:
  push:
    branches:
      - test-env
env:
  # COMMON deployment envs
  M3_ORGANIZATION: ${{github.event.organization.login}}
  M3_REPOSITORY: ${{github.event.repository.name}}
  M3_PROJECT: ghiras
  M3_COMPONENET: cms
  M3_ENVIRONMENT: dev
  M3_NAMESPACE: '${{github.event.organization.login}}-${{github.event.repository.name}}-dev'
  M3_DEPLOYMENT_PATH: deploy/cms
  M3_TEMP_DIR: temp
  M3_TEMP_SECRETS_DIR: temp-secrets
  M3_ENCRYPTION_PHRASE: ${{secrets.M3NTORSHIP_ENCRYPTION_PHRASE}}
  M3_ENCRYPTED_SECRETS_DIR: secrets
  M3_REPLICAS: '1'
  # posts service
  M3_DOCKER_FILE: Dockerfile
  M3_IMAGE: m3ntorshipci/ghiras-cms
  M3_PORT: '1337'
  M3_PORT_AR: '1338'
  M3_MEMORY: '200Mi'
  M3_CPU: '50m'

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # dynamic deployment envs
      - name: set templating envs
        id: version
        run: |          
          echo "M3_VERSION=dev-$(git rev-parse --short=4 ${{ github.sha }})" >> $GITHUB_ENV
  test:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - run: echo $M3_VERSION
  